name: slicer
description: Slicer, feito por Giovanna Godoy

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_circular_chart: ">=0.0.3"


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - cortes.jpg
    - slicer-logo.png
    - boi.jpg
    - header.jpg
    - vacas-2.jpg
    - legenda.jpg
